enum class TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, MINUS, PLUS,
    SEMICOLON, SLASH, STAR, COLON,

    NOT, NOT_EQUAL, EQUAL, EQUIVALENCE,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    AND, OR,
    WARD,
    GANK,
    TRUE,
    FALSE,
    FARM,
    FOR,
    BUY,
    CHAT_WHEEL,
    INVOKE,
    CAST,

    SPELL, MANA_COST, COOLDOWN,

    EOF
}