package hilicodenon

enum class TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, COLON,

    NOT, NOT_EQUAL,
    EQUAL, EQUIVALENCE,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    AND, CLASS, ELSE, FALSE, DEF, FOR, IF, OR, ELIF, CONTINUE,
    PRINT, RETURN, TRY, CASE, TRUE, BREAK, WHILE,

    EOF
}
